# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20180130_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='profile_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gram.Profile'),
        ),
    ]
