# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0010_auto_20180201_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='comment',
        ),
    ]
