# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0005_image_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes_number',
        ),
    ]
