# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0006_remove_like_likes_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='User does not have bio yet'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='User', max_length=30),
        ),
    ]
