# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0007_auto_20180207_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
